### ISSUE TITLE
[error] colors-custom-gtk3.css:1:33Invalid number for color value

### ISSUE THREAD

**Issue by Retr0astic** [cyberrumor/SwayEcosystem#2]
I'm getting this error when trying to add your configs to my setup, I'm not adding everything, just your waybar configs and have chosen transparent waybar from style,css.

Do you still use this setup? Do you get the same error?

**Comment by cyberrumor** [comment]
I don't have this setup anymore but it works via wal templates so make sure to copy `~/.config/wal/templates` folder to your system and run wal at least once before trying to launch waybar. Let me know if that doesn't fix your issue.

**Comment by Retr0astic** [comment]
That worked like a charm, thank you very much!

**Comment by cyberrumor** [comment]
You're very welcome, don't be afraid to reach out if you need anything else. Thanks for checking out my dots!
